sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose build unrasterize
  # - docker exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"

install: true

script:
  - make lint
  - make coverage

after_success:
  - coveralls data_file=data/.coverage
